logging:
  level:
    com.giraone: DEBUG
    org:
      springframework:
        ws: DEBUG
server:
  port: 8081

application:
  soapEndpointUrl: 'http://localhost:8080/ws/bank'
  defaultUri: 'http://www.giraone.com/blz-service/'